export const indianFoodCalories = [
  { "food": "Butter Chicken", "calories": 490 },
  { "food": "Paneer Butter Masala", "calories": 412 },
  { "food": "Dal Makhani", "calories": 330 },
  { "food": "Aloo Paratha", "calories": 290 },
  { "food": "Chole Bhature", "calories": 427 },
  { "food": "Chicken Biryani", "calories": 480 },
  { "food": "Vegetable Biryani", "calories": 390 },
  { "food": "Idli", "calories": 50 },
  { "food": "Masala Dosa", "calories": 206 },
  { "food": "Samosa", "calories": 262 },
  { "food": "Medu Vada", "calories": 97 },
  { "food": "Pani Puri", "calories": 36 },
  { "food": "Pav Bhaji", "calories": 400 },
  { "food": "Bhindi Masala", "calories": 120 },
  { "food": "Rajma Chawal", "calories": 346 },
  { "food": "Palak Paneer", "calories": 240 },
  { "food": "Kheer", "calories": 310 },
  { "food": "Rasgulla", "calories": 120 },
  { "food": "Gulab Jamun", "calories": 150 },
  { "food": "Lassi", "calories": 260 },
  { "food": "Aloo Gobi", "calories": 150 },
  { "food": "Fish Curry", "calories": 280 },
  { "food": "Tandoori Chicken", "calories": 320 },
  { "food": "Baingan Bharta", "calories": 130 },
  { "food": "Matar Paneer", "calories": 300 },
  { "food": "Pulao", "calories": 320 },
  { "food": "Poha", "calories": 180 },
  { "food": "Upma", "calories": 220 },
  { "food": "Chaat", "calories": 210 },
  { "food": "Dhokla", "calories": 152 },
  { "food": "Vada Pav", "calories": 290 },
  { "food": "Bhel Puri", "calories": 120 },
  { "food": "Thepla", "calories": 120 },
  { "food": "Khichdi", "calories": 270 },
  { "food": "Shahi Paneer", "calories": 350 },
  { "food": "Chicken Curry", "calories": 300 },
  { "food": "Malai Kofta", "calories": 400 },
  { "food": "Roti", "calories": 120 },
  { "food": "Naan", "calories": 262 },
  { "food": "Pesarattu", "calories": 158 },
  { "food": "Mysore Pak", "calories": 562 },
  { "food": "Jalebi", "calories": 150 },
  { "food": "Kulfi", "calories": 207 },
  { "food": "Pongal", "calories": 206 },
  { "food": "Kadhi Pakora", "calories": 230 },
  { "food": "Mutton Curry", "calories": 320 },
  { "food": "Egg Curry", "calories": 170 },
  { "food": "Bhature", "calories": 325 },
  { "food": "Dum Aloo", "calories": 274 },
  { "food": "Sheer Khurma", "calories": 380 },
  { "food": "Mango Lassi", "calories": 300 },
];



export const exercises = [
  {
    name: "Push-Up",
    targetMuscles: ["Chest ", "Shoulders ", "Triceps ", "Core "],
    tag: "Beginner Friendly",
  },
  {
    name: "Pull-Up",
    targetMuscles: ["Back ", "Biceps ", "Shoulders "],
    tag: "Advanced",
  },
  {
    name: "Squat",
    targetMuscles: ["Quadriceps ", "Glutes ", "Hamstrings ", "Core "],
    tag: "Beginner Friendly",
  },
  {
    name: "Plank",
    targetMuscles: ["Core ", "Shoulders "],
    tag: "Beginner Friendly",
  },
  {
    name: "Deadlift",
    targetMuscles: ["Hamstrings ", "Glutes ", "Lower Back "],
    tag: "Advanced",
  },
  {
    name: "Lunges",
    targetMuscles: ["Quadriceps ", "Glutes ", "Hamstrings ", "Calves "],
    tag: "Average",
  },
  {
    name: "Bicep Curl",
    targetMuscles: ["Biceps "],
    tag: "Beginner Friendly",
  },
  {
    name: "Bench Press",
    targetMuscles: ["Chest ", "Triceps ", "Shoulders "],
    tag: "Average",
  },
  {
    name: "Overhead Press",
    targetMuscles: ["Shoulders ", "Triceps "],
    tag: "Average",
  },
  {
    name: "Burpees",
    targetMuscles: ["Full Body ", "Cardio "],
    tag: "Advanced",
  },
  {
    name: "Mountain Climbers",
    targetMuscles: ["Core ", "Shoulders ", "Cardio "],
    tag: "Beginner Friendly",
  },
  {
    name: "Leg Press",
    targetMuscles: ["Quadriceps ", "Hamstrings ", "Glutes "],
    tag: "Average",
  },
  {
    name: "Russian Twists",
    targetMuscles: ["Obliques ", "Core "],
    tag: "Beginner Friendly",
  },
  {
    name: "Lat Pulldown",
    targetMuscles: ["Back ", "Biceps "],
    tag: "Average",
  },
  {
    name: "Dumbbell Row",
    targetMuscles: ["Back ", "Biceps "],
    tag: "Average",
  },
  {
    name: "Tricep Dips",
    targetMuscles: ["Triceps ", "Shoulders ", "Chest "],
    tag: "Beginner Friendly",
  },
  {
    name: "Side Plank",
    targetMuscles: ["Obliques ", "Core "],
    tag: "Beginner Friendly",
  },
  {
    name: "Box Jumps",
    targetMuscles: ["Quadriceps ", "Glutes ", "Hamstrings ", "Calves "],
    tag: "Advanced",
  },
  {
    name: "Jump Rope",
    targetMuscles: ["Cardio ", "Full Body "],
    tag: "Beginner Friendly",
  },
  {
    name: "Kettlebell Swings",
    targetMuscles: ["Glutes ", "Hamstrings ", "Shoulders ", "Core "],
    tag: "Average",
  },
  {
    name: "Wall Sit",
    targetMuscles: ["Quadriceps ", "Glutes ", "Core "],
    tag: "Beginner Friendly",
  },
  {
    name: "Pistol Squat",
    targetMuscles: ["Quadriceps ", "Glutes ", "Hamstrings ", "Core "],
    tag: "Advanced",
  },
  {
    name: "Spinning",
    targetMuscles: ["Cardio ", "Legs "],
    tag: "Beginner Friendly",
  },
  {
    name: "Arnold Press",
    targetMuscles: ["Shoulders ", "Triceps "],
    tag: "Average",
  },
  {
    name: "Hip Thrusts",
    targetMuscles: ["Glutes ", "Hamstrings "],
    tag: "Average",
  },
  {
    name: "High Knees",
    targetMuscles: ["Cardio ", "Core "],
    tag: "Beginner Friendly",
  },
  {
    name: "Calf Raises",
    targetMuscles: ["Calves "],
    tag: "Beginner Friendly",
  },
  {
    name: "Barbell Row",
    targetMuscles: ["Back ", "Biceps "],
    tag: "Advanced",
  },
  {
    name: "Chest Fly",
    targetMuscles: ["Chest ", "Shoulders "],
    tag: "Average",
  },
  {
    name: "Seated Leg Curl",
    targetMuscles: ["Hamstrings "],
    tag: "Beginner Friendly",
  },
  {
    name: "Face Pull",
    targetMuscles: ["Rear Delts ", "Shoulders "],
    tag: "Average",
  },
  {
    name: "Jump Squats",
    targetMuscles: ["Quadriceps ", "Glutes ", "Hamstrings ", "Cardio "],
    tag: "Advanced",
  },
  {
    name: "Handstand Push-Up",
    targetMuscles: ["Shoulders ", "Triceps ", "Core "],
    tag: "Advanced",
  },
  {
    name: "Farmer's Carry",
    targetMuscles: ["Core ", "Forearms "],
    tag: "Average",
  },
  {
    name: "Good Mornings",
    targetMuscles: ["Hamstrings ", "Lower Back ", "Glutes "],
    tag: "Average",
  },
  {
    name: "Zercher Squat",
    targetMuscles: ["Quadriceps ", "Glutes ", "Core "],
    tag: "Advanced",
  },
  {
    name: "Pull Aparts",
    targetMuscles: ["Rear Delts ", "Shoulders "],
    tag: "Beginner Friendly",
  },
  {
    name: "Rowing Machine",
    targetMuscles: ["Cardio ", "Back ", "Core "],
    tag: "Beginner Friendly",
  },
  {
    name: "Skater Jumps",
    targetMuscles: ["Glutes ", "Quads ", "Core ", "Cardio "],
    tag: "Advanced",
  },
  {
    name: "Chin-Up",
    targetMuscles: ["Biceps ", "Back "],
    tag: "Advanced",
  },
  {
    name: "Incline Dumbbell Press",
    targetMuscles: ["Chest ", "Shoulders ", "Triceps "],
    tag: "Average",
  },
  {
    name: "Medicine Ball Slam",
    targetMuscles: ["Core ", "Shoulders ", "Cardio "],
    tag: "Average",
  },
  {
    name: "Donkey Kicks",
    targetMuscles: ["Glutes "],
    tag: "Beginner Friendly",
  },
  {
    name: "Side Lunges",
    targetMuscles: ["Quadriceps ", "Glutes ", "Hamstrings "],
    tag: "Average",
  },
  {
    name: "Swiss Ball Crunch",
    targetMuscles: ["Core "],
    tag: "Beginner Friendly",
  },
  {
    name: "Hanging Leg Raise",
    targetMuscles: ["Core ", "Hip Flexors "],
    tag: "Advanced",
  },
  {
    name: "Windshield Wipers",
    targetMuscles: ["Core ", "Obliques "],
    tag: "Advanced",
  },
];

